<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="c:\rip\SddConf.Properties\PhoneNumbers\bin\Debug\PhoneNumbers.dll" total="1" errors="1" failures="0" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2015-05-14" time="08:20:01">
  <environment nunit-version="2.6.3.13283" clr-version="2.0.50727.8000" os-version="Microsoft Windows NT 6.2.9200.0" platform="Win32NT" cwd="c:\rip\SddConf.Properties\PhoneNumbers" machine-name="FREDONIA" user="Michael.Newton" user-domain="15BELOW" />
  <culture-info current-culture="en-GB" current-uiculture="en-US" />
  <test-suite type="Assembly" name="c:\rip\SddConf.Properties\PhoneNumbers\bin\Debug\PhoneNumbers.dll" executed="True" result="Failure" success="False" time="1.079" asserts="0">
    <results>
      <test-suite type="Namespace" name="PhoneNumbers" executed="True" result="Failure" success="False" time="1.061" asserts="0">
        <results>
          <test-suite type="Namespace" name="Test" executed="True" result="Failure" success="False" time="1.060" asserts="0">
            <results>
              <test-suite type="TestFixture" name="ValidE164Tests" executed="True" result="Failure" success="False" time="1.057" asserts="0">
                <results>
                  <test-case name="PhoneNumbers.Test.ValidE164Tests.test_TryCreate" executed="True" result="Error" success="False" time="1.039" asserts="0">
                    <failure>
                      <message><![CDATA[System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----> System.Exception : ValidE164Properties.InvalidNumbersAreInvalid-Falsifiable, after 1 test (0 shrinks) (StdGen (1434691358,296007800)):
Label of failing property: +607194543889972D
< +607194543889972D >
]]></message>
                      <stack-trace><![CDATA[at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at FsCheck.Runner.checkMethod(Config config, MethodInfo m, FSharpOption`1 target) in C:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 304
at FsCheck.Runner.checkAll(Config config, Type t) in C:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 311
at PhoneNumbers.Test.ValidE164Tests.test_TryCreate() in c:\rip\SddConf.Properties\PhoneNumbers\ValidE164.cs:line 127
--Exception
at <StartupCode$FsCheck>.$Runner.get_throwingRunner@350-1.Invoke(String message) in C:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 350
at FsCheck.Runner.check[a](Config config, a p) in C:\Users\Kurt\Projects\FsCheck\fsharp\src\FsCheck\Runner.fs:line 267
]]></stack-trace>
                    </failure>
                  </test-case>
                </results>
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>